services:
    my_handler:
      class: Wsza\Bundle\ReportBundle\Serializer\ForeignKeyType
      tags:
        - { name: jms_serializer.handler, direction: serialization, format: json, type: Integer}
      arguments:
        - { type: service, id: @doctrine.orm.entity_manager }
#    report.example:
#        class: Wsza\Bundle\ReportBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
