#services:
#    my_handler:
#      class: Wsza\Bundle\ReportBundle\Serializer\ForeignKeyType
#      tags:
#        - { name: jms_serializer.subscribing_handler, format: json }
#      arguments: [@my_manager]
#    my_manager:
#      class: Sonata\OrderBundle\Entity\OrderManager
#      arguments: [Wsza\Bundle\ReportBundle\Entity\Subscriber, @doctrine]
#    report.example:
#        class: Wsza\Bundle\ReportBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
  foreignHandler:
      class:     Wsza\Bundle\ReportBundle\Serializer\ForeignKeyHandler
      tags:
          - { name: jms_serializer.subscribing_handler }


  # admin services
  sonata.admin.client:
          class: Wsza\Bundle\ReportBundle\Admin\ClientAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Client" }
          arguments:
              - ~
              - Wsza\Bundle\ReportBundle\Entity\Client
              - ~
          calls:
              - [ setTranslationDomain, [ReportBundle]]
  sonata.admin.subscriber:
          class: Wsza\Bundle\ReportBundle\Admin\SubscriberAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Subscriber" }
          arguments:
              - ~
              - Wsza\Bundle\ReportBundle\Entity\Subscriber
              - ~
          calls:
              - [ setTranslationDomain, [ReportBundle]]
  sonata.admin.tariff:
          class: Wsza\Bundle\ReportBundle\Admin\TariffAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Tariff" }
          arguments:
              - ~
              - Wsza\Bundle\ReportBundle\Entity\Tariff
              - ~
          calls:
              - [ setTranslationDomain, [ReportBundle]]
  sonata.admin.connection:
          class: Wsza\Bundle\ReportBundle\Admin\ConnectionAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Connection" }
          arguments:
              - ~
              - Wsza\Bundle\ReportBundle\Entity\Connection
              - ~
          calls:
              - [ setTranslationDomain, [ReportBundle]]
  sonata.admin.report:
          class: Wsza\Bundle\ReportBundle\Admin\ReportAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Report" }
          arguments:
              - ~
              - Wsza\Bundle\ReportBundle\Entity\Report
              - ~
          calls:
              - [ setTranslationDomain, [ReportBundle]]
